AllCops:
  Exclude:
    - vendor/**/*
    - db/schema.rb
    - db/fixtures/**/*
    - bin/**
    - node_modules/**/*

Metrics/AbcSize:
  Max: 35

Layout/LineLength:
  Max: 160

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%": "{}"
    "%i": "()"
    "%w": "()"
Metrics/BlockLength:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/GlobalVars:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true
