name: CI
on: 
  push:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
jobs:
  build:
    name: RSpec
    runs-on: ubuntu-latest
    container:
      image: ruby:2.7.1
      volumes:
        - bundle_cache:/usr/local/bundle
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v1
        with:
          path: /usr/local/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: install node, yarn
        run: |
          curl -sL https://deb.nodesource.com/setup_12.x | bash -
          apt-get install -y nodejs
          npm install -g yarn
          yarn upgrade
      - name: bundle install
        run: |
          bundle config set path 'vendor/bundle'
          bundle install --jobs 4 --retry 3
      - name: setup database
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:migrate
      - name: run RSpec
        run: |
          bundle exec rspec
